python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 0 -o mash_cos_sim_mat_k_21_seed_0
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 0 -o mash_cos_sim_mat_k_31_seed_0
python make_sketches.py -g ../ecoli_genomes/ -k 41 -s 0 -o mash_cos_sim_mat_k_41_seed_0
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 0 -o mash_cos_sim_mat_k_21_seed_1
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 0 -o mash_cos_sim_mat_k_31_seed_1
python make_sketches.py -g ../ecoli_genomes/ -k 41 -s 0 -o mash_cos_sim_mat_k_41_seed_1
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 0 -o mash_cos_sim_mat_k_21_seed_2
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 0 -o mash_cos_sim_mat_k_31_seed_2
python make_sketches.py -g ../ecoli_genomes/ -k 41 -s 0 -o mash_cos_sim_mat_k_41_seed_2
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 0 -o mash_cos_sim_mat_k_21_seed_3
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 0 -o mash_cos_sim_mat_k_31_seed_3
python make_sketches.py -g ../ecoli_genomes/ -k 41 -s 0 -o mash_cos_sim_mat_k_41_seed_3
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 0 -o mash_cos_sim_mat_k_21_seed_4
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 0 -o mash_cos_sim_mat_k_31_seed_4
python make_sketches.py -g ../ecoli_genomes/ -k 41 -s 0 -o mash_cos_sim_mat_k_41_seed_4
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 0 -o mash_cos_sim_mat_k_21_seed_5
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 0 -o mash_cos_sim_mat_k_31_seed_5
python make_sketches.py -g ../ecoli_genomes/ -k 41 -s 0 -o mash_cos_sim_mat_k_41_seed_5
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 0 -o mash_cos_sim_mat_k_21_seed_6
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 0 -o mash_cos_sim_mat_k_31_seed_6
python make_sketches.py -g ../ecoli_genomes/ -k 41 -s 0 -o mash_cos_sim_mat_k_41_seed_6
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 0 -o mash_cos_sim_mat_k_21_seed_7
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 0 -o mash_cos_sim_mat_k_31_seed_7
python make_sketches.py -g ../ecoli_genomes/ -k 41 -s 0 -o mash_cos_sim_mat_k_41_seed_7
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 0 -o mash_cos_sim_mat_k_21_seed_8
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 0 -o mash_cos_sim_mat_k_31_seed_8
python make_sketches.py -g ../ecoli_genomes/ -k 41 -s 0 -o mash_cos_sim_mat_k_41_seed_8
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 0 -o mash_cos_sim_mat_k_21_seed_9
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 0 -o mash_cos_sim_mat_k_31_seed_9
python make_sketches.py -g ../ecoli_genomes/ -k 41 -s 0 -o mash_cos_sim_mat_k_41_seed_9
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 0 -o mash_cos_sim_mat_k_21_seed_10
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 0 -o mash_cos_sim_mat_k_31_seed_10
python make_sketches.py -g ../ecoli_genomes/ -k 41 -s 0 -o mash_cos_sim_mat_k_41_seed_10
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 0 -o mash_cos_sim_mat_k_21_seed_11
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 0 -o mash_cos_sim_mat_k_31_seed_11
python make_sketches.py -g ../ecoli_genomes/ -k 41 -s 0 -o mash_cos_sim_mat_k_41_seed_11
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 0 -o mash_cos_sim_mat_k_21_seed_12
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 0 -o mash_cos_sim_mat_k_31_seed_12
python make_sketches.py -g ../ecoli_genomes/ -k 41 -s 0 -o mash_cos_sim_mat_k_41_seed_12
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 0 -o mash_cos_sim_mat_k_21_seed_13
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 0 -o mash_cos_sim_mat_k_31_seed_13
python make_sketches.py -g ../ecoli_genomes/ -k 41 -s 0 -o mash_cos_sim_mat_k_41_seed_13
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 0 -o mash_cos_sim_mat_k_21_seed_14
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 0 -o mash_cos_sim_mat_k_31_seed_14
python make_sketches.py -g ../ecoli_genomes/ -k 41 -s 0 -o mash_cos_sim_mat_k_41_seed_14
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 0 -o mash_cos_sim_mat_k_21_seed_15
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 0 -o mash_cos_sim_mat_k_31_seed_15
python make_sketches.py -g ../ecoli_genomes/ -k 41 -s 0 -o mash_cos_sim_mat_k_41_seed_15
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 0 -o mash_cos_sim_mat_k_21_seed_16
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 0 -o mash_cos_sim_mat_k_31_seed_16
python make_sketches.py -g ../ecoli_genomes/ -k 41 -s 0 -o mash_cos_sim_mat_k_41_seed_16
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 0 -o mash_cos_sim_mat_k_21_seed_17
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 0 -o mash_cos_sim_mat_k_31_seed_17
python make_sketches.py -g ../ecoli_genomes/ -k 41 -s 0 -o mash_cos_sim_mat_k_41_seed_17
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 0 -o mash_cos_sim_mat_k_21_seed_18
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 0 -o mash_cos_sim_mat_k_31_seed_18
python make_sketches.py -g ../ecoli_genomes/ -k 41 -s 0 -o mash_cos_sim_mat_k_41_seed_18
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 0 -o mash_cos_sim_mat_k_21_seed_19
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 0 -o mash_cos_sim_mat_k_31_seed_19
python make_sketches.py -g ../ecoli_genomes/ -k 41 -s 0 -o mash_cos_sim_mat_k_41_seed_19
