python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 20 -o mash_cos_sim_mat_k_11_seed_20
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 21 -o mash_cos_sim_mat_k_11_seed_21
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 22 -o mash_cos_sim_mat_k_11_seed_22
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 23 -o mash_cos_sim_mat_k_11_seed_23
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 24 -o mash_cos_sim_mat_k_11_seed_24
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 25 -o mash_cos_sim_mat_k_11_seed_25
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 26 -o mash_cos_sim_mat_k_11_seed_26
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 27 -o mash_cos_sim_mat_k_11_seed_27
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 28 -o mash_cos_sim_mat_k_11_seed_28
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 29 -o mash_cos_sim_mat_k_11_seed_29
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 30 -o mash_cos_sim_mat_k_11_seed_30
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 31 -o mash_cos_sim_mat_k_11_seed_31
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 32 -o mash_cos_sim_mat_k_11_seed_32
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 33 -o mash_cos_sim_mat_k_11_seed_33
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 34 -o mash_cos_sim_mat_k_11_seed_34
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 35 -o mash_cos_sim_mat_k_11_seed_35
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 36 -o mash_cos_sim_mat_k_11_seed_36
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 37 -o mash_cos_sim_mat_k_11_seed_37
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 38 -o mash_cos_sim_mat_k_11_seed_38
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 39 -o mash_cos_sim_mat_k_11_seed_39
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 40 -o mash_cos_sim_mat_k_11_seed_40
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 41 -o mash_cos_sim_mat_k_11_seed_41
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 42 -o mash_cos_sim_mat_k_11_seed_42
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 43 -o mash_cos_sim_mat_k_11_seed_43
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 44 -o mash_cos_sim_mat_k_11_seed_44
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 45 -o mash_cos_sim_mat_k_11_seed_45
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 46 -o mash_cos_sim_mat_k_11_seed_46
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 47 -o mash_cos_sim_mat_k_11_seed_47
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 48 -o mash_cos_sim_mat_k_11_seed_48
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 49 -o mash_cos_sim_mat_k_11_seed_49
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 50 -o mash_cos_sim_mat_k_11_seed_50
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 51 -o mash_cos_sim_mat_k_11_seed_51
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 52 -o mash_cos_sim_mat_k_11_seed_52
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 53 -o mash_cos_sim_mat_k_11_seed_53
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 54 -o mash_cos_sim_mat_k_11_seed_54
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 55 -o mash_cos_sim_mat_k_11_seed_55
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 56 -o mash_cos_sim_mat_k_11_seed_56
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 57 -o mash_cos_sim_mat_k_11_seed_57
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 58 -o mash_cos_sim_mat_k_11_seed_58
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 59 -o mash_cos_sim_mat_k_11_seed_59
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 60 -o mash_cos_sim_mat_k_11_seed_60
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 61 -o mash_cos_sim_mat_k_11_seed_61
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 62 -o mash_cos_sim_mat_k_11_seed_62
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 63 -o mash_cos_sim_mat_k_11_seed_63
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 64 -o mash_cos_sim_mat_k_11_seed_64
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 65 -o mash_cos_sim_mat_k_11_seed_65
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 66 -o mash_cos_sim_mat_k_11_seed_66
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 67 -o mash_cos_sim_mat_k_11_seed_67
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 68 -o mash_cos_sim_mat_k_11_seed_68
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 69 -o mash_cos_sim_mat_k_11_seed_69
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 70 -o mash_cos_sim_mat_k_11_seed_70
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 71 -o mash_cos_sim_mat_k_11_seed_71
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 72 -o mash_cos_sim_mat_k_11_seed_72
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 73 -o mash_cos_sim_mat_k_11_seed_73
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 74 -o mash_cos_sim_mat_k_11_seed_74
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 75 -o mash_cos_sim_mat_k_11_seed_75
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 76 -o mash_cos_sim_mat_k_11_seed_76
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 77 -o mash_cos_sim_mat_k_11_seed_77
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 78 -o mash_cos_sim_mat_k_11_seed_78
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 79 -o mash_cos_sim_mat_k_11_seed_79
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 80 -o mash_cos_sim_mat_k_11_seed_80
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 81 -o mash_cos_sim_mat_k_11_seed_81
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 82 -o mash_cos_sim_mat_k_11_seed_82
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 83 -o mash_cos_sim_mat_k_11_seed_83
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 84 -o mash_cos_sim_mat_k_11_seed_84
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 85 -o mash_cos_sim_mat_k_11_seed_85
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 86 -o mash_cos_sim_mat_k_11_seed_86
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 87 -o mash_cos_sim_mat_k_11_seed_87
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 88 -o mash_cos_sim_mat_k_11_seed_88
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 89 -o mash_cos_sim_mat_k_11_seed_89
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 90 -o mash_cos_sim_mat_k_11_seed_90
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 91 -o mash_cos_sim_mat_k_11_seed_91
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 92 -o mash_cos_sim_mat_k_11_seed_92
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 93 -o mash_cos_sim_mat_k_11_seed_93
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 94 -o mash_cos_sim_mat_k_11_seed_94
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 95 -o mash_cos_sim_mat_k_11_seed_95
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 96 -o mash_cos_sim_mat_k_11_seed_96
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 97 -o mash_cos_sim_mat_k_11_seed_97
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 98 -o mash_cos_sim_mat_k_11_seed_98
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 99 -o mash_cos_sim_mat_k_11_seed_99
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 20 -o mash_cos_sim_mat_k_21_seed_20
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 21 -o mash_cos_sim_mat_k_21_seed_21
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 22 -o mash_cos_sim_mat_k_21_seed_22
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 23 -o mash_cos_sim_mat_k_21_seed_23
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 24 -o mash_cos_sim_mat_k_21_seed_24
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 25 -o mash_cos_sim_mat_k_21_seed_25
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 26 -o mash_cos_sim_mat_k_21_seed_26
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 27 -o mash_cos_sim_mat_k_21_seed_27
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 28 -o mash_cos_sim_mat_k_21_seed_28
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 29 -o mash_cos_sim_mat_k_21_seed_29
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 30 -o mash_cos_sim_mat_k_21_seed_30
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 31 -o mash_cos_sim_mat_k_21_seed_31
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 32 -o mash_cos_sim_mat_k_21_seed_32
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 33 -o mash_cos_sim_mat_k_21_seed_33
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 34 -o mash_cos_sim_mat_k_21_seed_34
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 35 -o mash_cos_sim_mat_k_21_seed_35
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 36 -o mash_cos_sim_mat_k_21_seed_36
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 37 -o mash_cos_sim_mat_k_21_seed_37
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 38 -o mash_cos_sim_mat_k_21_seed_38
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 39 -o mash_cos_sim_mat_k_21_seed_39
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 40 -o mash_cos_sim_mat_k_21_seed_40
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 41 -o mash_cos_sim_mat_k_21_seed_41
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 42 -o mash_cos_sim_mat_k_21_seed_42
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 43 -o mash_cos_sim_mat_k_21_seed_43
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 44 -o mash_cos_sim_mat_k_21_seed_44
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 45 -o mash_cos_sim_mat_k_21_seed_45
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 46 -o mash_cos_sim_mat_k_21_seed_46
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 47 -o mash_cos_sim_mat_k_21_seed_47
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 48 -o mash_cos_sim_mat_k_21_seed_48
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 49 -o mash_cos_sim_mat_k_21_seed_49
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 50 -o mash_cos_sim_mat_k_21_seed_50
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 51 -o mash_cos_sim_mat_k_21_seed_51
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 52 -o mash_cos_sim_mat_k_21_seed_52
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 53 -o mash_cos_sim_mat_k_21_seed_53
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 54 -o mash_cos_sim_mat_k_21_seed_54
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 55 -o mash_cos_sim_mat_k_21_seed_55
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 56 -o mash_cos_sim_mat_k_21_seed_56
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 57 -o mash_cos_sim_mat_k_21_seed_57
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 58 -o mash_cos_sim_mat_k_21_seed_58
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 59 -o mash_cos_sim_mat_k_21_seed_59
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 60 -o mash_cos_sim_mat_k_21_seed_60
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 61 -o mash_cos_sim_mat_k_21_seed_61
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 62 -o mash_cos_sim_mat_k_21_seed_62
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 63 -o mash_cos_sim_mat_k_21_seed_63
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 64 -o mash_cos_sim_mat_k_21_seed_64
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 65 -o mash_cos_sim_mat_k_21_seed_65
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 66 -o mash_cos_sim_mat_k_21_seed_66
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 67 -o mash_cos_sim_mat_k_21_seed_67
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 68 -o mash_cos_sim_mat_k_21_seed_68
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 69 -o mash_cos_sim_mat_k_21_seed_69
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 70 -o mash_cos_sim_mat_k_21_seed_70
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 71 -o mash_cos_sim_mat_k_21_seed_71
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 72 -o mash_cos_sim_mat_k_21_seed_72
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 73 -o mash_cos_sim_mat_k_21_seed_73
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 74 -o mash_cos_sim_mat_k_21_seed_74
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 75 -o mash_cos_sim_mat_k_21_seed_75
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 76 -o mash_cos_sim_mat_k_21_seed_76
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 77 -o mash_cos_sim_mat_k_21_seed_77
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 78 -o mash_cos_sim_mat_k_21_seed_78
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 79 -o mash_cos_sim_mat_k_21_seed_79
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 80 -o mash_cos_sim_mat_k_21_seed_80
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 81 -o mash_cos_sim_mat_k_21_seed_81
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 82 -o mash_cos_sim_mat_k_21_seed_82
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 83 -o mash_cos_sim_mat_k_21_seed_83
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 84 -o mash_cos_sim_mat_k_21_seed_84
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 85 -o mash_cos_sim_mat_k_21_seed_85
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 86 -o mash_cos_sim_mat_k_21_seed_86
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 87 -o mash_cos_sim_mat_k_21_seed_87
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 88 -o mash_cos_sim_mat_k_21_seed_88
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 89 -o mash_cos_sim_mat_k_21_seed_89
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 90 -o mash_cos_sim_mat_k_21_seed_90
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 91 -o mash_cos_sim_mat_k_21_seed_91
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 92 -o mash_cos_sim_mat_k_21_seed_92
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 93 -o mash_cos_sim_mat_k_21_seed_93
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 94 -o mash_cos_sim_mat_k_21_seed_94
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 95 -o mash_cos_sim_mat_k_21_seed_95
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 96 -o mash_cos_sim_mat_k_21_seed_96
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 97 -o mash_cos_sim_mat_k_21_seed_97
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 98 -o mash_cos_sim_mat_k_21_seed_98
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 99 -o mash_cos_sim_mat_k_21_seed_99
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 20 -o mash_cos_sim_mat_k_31_seed_20
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 21 -o mash_cos_sim_mat_k_31_seed_21
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 22 -o mash_cos_sim_mat_k_31_seed_22
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 23 -o mash_cos_sim_mat_k_31_seed_23
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 24 -o mash_cos_sim_mat_k_31_seed_24
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 25 -o mash_cos_sim_mat_k_31_seed_25
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 26 -o mash_cos_sim_mat_k_31_seed_26
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 27 -o mash_cos_sim_mat_k_31_seed_27
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 28 -o mash_cos_sim_mat_k_31_seed_28
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 29 -o mash_cos_sim_mat_k_31_seed_29
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 30 -o mash_cos_sim_mat_k_31_seed_30
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 31 -o mash_cos_sim_mat_k_31_seed_31
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 32 -o mash_cos_sim_mat_k_31_seed_32
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 33 -o mash_cos_sim_mat_k_31_seed_33
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 34 -o mash_cos_sim_mat_k_31_seed_34
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 35 -o mash_cos_sim_mat_k_31_seed_35
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 36 -o mash_cos_sim_mat_k_31_seed_36
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 37 -o mash_cos_sim_mat_k_31_seed_37
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 38 -o mash_cos_sim_mat_k_31_seed_38
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 39 -o mash_cos_sim_mat_k_31_seed_39
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 40 -o mash_cos_sim_mat_k_31_seed_40
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 41 -o mash_cos_sim_mat_k_31_seed_41
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 42 -o mash_cos_sim_mat_k_31_seed_42
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 43 -o mash_cos_sim_mat_k_31_seed_43
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 44 -o mash_cos_sim_mat_k_31_seed_44
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 45 -o mash_cos_sim_mat_k_31_seed_45
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 46 -o mash_cos_sim_mat_k_31_seed_46
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 47 -o mash_cos_sim_mat_k_31_seed_47
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 48 -o mash_cos_sim_mat_k_31_seed_48
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 49 -o mash_cos_sim_mat_k_31_seed_49
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 50 -o mash_cos_sim_mat_k_31_seed_50
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 51 -o mash_cos_sim_mat_k_31_seed_51
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 52 -o mash_cos_sim_mat_k_31_seed_52
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 53 -o mash_cos_sim_mat_k_31_seed_53
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 54 -o mash_cos_sim_mat_k_31_seed_54
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 55 -o mash_cos_sim_mat_k_31_seed_55
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 56 -o mash_cos_sim_mat_k_31_seed_56
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 57 -o mash_cos_sim_mat_k_31_seed_57
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 58 -o mash_cos_sim_mat_k_31_seed_58
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 59 -o mash_cos_sim_mat_k_31_seed_59
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 60 -o mash_cos_sim_mat_k_31_seed_60
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 61 -o mash_cos_sim_mat_k_31_seed_61
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 62 -o mash_cos_sim_mat_k_31_seed_62
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 63 -o mash_cos_sim_mat_k_31_seed_63
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 64 -o mash_cos_sim_mat_k_31_seed_64
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 65 -o mash_cos_sim_mat_k_31_seed_65
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 66 -o mash_cos_sim_mat_k_31_seed_66
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 67 -o mash_cos_sim_mat_k_31_seed_67
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 68 -o mash_cos_sim_mat_k_31_seed_68
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 69 -o mash_cos_sim_mat_k_31_seed_69
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 70 -o mash_cos_sim_mat_k_31_seed_70
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 71 -o mash_cos_sim_mat_k_31_seed_71
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 72 -o mash_cos_sim_mat_k_31_seed_72
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 73 -o mash_cos_sim_mat_k_31_seed_73
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 74 -o mash_cos_sim_mat_k_31_seed_74
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 75 -o mash_cos_sim_mat_k_31_seed_75
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 76 -o mash_cos_sim_mat_k_31_seed_76
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 77 -o mash_cos_sim_mat_k_31_seed_77
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 78 -o mash_cos_sim_mat_k_31_seed_78
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 79 -o mash_cos_sim_mat_k_31_seed_79
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 80 -o mash_cos_sim_mat_k_31_seed_80
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 81 -o mash_cos_sim_mat_k_31_seed_81
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 82 -o mash_cos_sim_mat_k_31_seed_82
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 83 -o mash_cos_sim_mat_k_31_seed_83
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 84 -o mash_cos_sim_mat_k_31_seed_84
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 85 -o mash_cos_sim_mat_k_31_seed_85
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 86 -o mash_cos_sim_mat_k_31_seed_86
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 87 -o mash_cos_sim_mat_k_31_seed_87
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 88 -o mash_cos_sim_mat_k_31_seed_88
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 89 -o mash_cos_sim_mat_k_31_seed_89
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 90 -o mash_cos_sim_mat_k_31_seed_90
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 91 -o mash_cos_sim_mat_k_31_seed_91
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 92 -o mash_cos_sim_mat_k_31_seed_92
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 93 -o mash_cos_sim_mat_k_31_seed_93
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 94 -o mash_cos_sim_mat_k_31_seed_94
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 95 -o mash_cos_sim_mat_k_31_seed_95
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 96 -o mash_cos_sim_mat_k_31_seed_96
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 97 -o mash_cos_sim_mat_k_31_seed_97
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 98 -o mash_cos_sim_mat_k_31_seed_98
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 99 -o mash_cos_sim_mat_k_31_seed_99
