python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 0 -o mash_cos_sim_mat_k_11_seed_0
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 0 -o mash_cos_sim_mat_k_11_seed_1
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 0 -o mash_cos_sim_mat_k_11_seed_2
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 0 -o mash_cos_sim_mat_k_11_seed_3
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 0 -o mash_cos_sim_mat_k_11_seed_4
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 0 -o mash_cos_sim_mat_k_11_seed_5
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 0 -o mash_cos_sim_mat_k_11_seed_6
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 0 -o mash_cos_sim_mat_k_11_seed_7
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 0 -o mash_cos_sim_mat_k_11_seed_8
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 0 -o mash_cos_sim_mat_k_11_seed_9
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 0 -o mash_cos_sim_mat_k_11_seed_10
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 0 -o mash_cos_sim_mat_k_11_seed_11
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 0 -o mash_cos_sim_mat_k_11_seed_12
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 0 -o mash_cos_sim_mat_k_11_seed_13
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 0 -o mash_cos_sim_mat_k_11_seed_14
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 0 -o mash_cos_sim_mat_k_11_seed_15
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 0 -o mash_cos_sim_mat_k_11_seed_16
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 0 -o mash_cos_sim_mat_k_11_seed_17
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 0 -o mash_cos_sim_mat_k_11_seed_18
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 0 -o mash_cos_sim_mat_k_11_seed_19
