python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 0 -o mash_cos_sim_mat_k_11_seed_0
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 1 -o mash_cos_sim_mat_k_11_seed_1
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 2 -o mash_cos_sim_mat_k_11_seed_2
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 3 -o mash_cos_sim_mat_k_11_seed_3
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 4 -o mash_cos_sim_mat_k_11_seed_4
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 5 -o mash_cos_sim_mat_k_11_seed_5
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 6 -o mash_cos_sim_mat_k_11_seed_6
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 7 -o mash_cos_sim_mat_k_11_seed_7
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 8 -o mash_cos_sim_mat_k_11_seed_8
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 9 -o mash_cos_sim_mat_k_11_seed_9
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 10 -o mash_cos_sim_mat_k_11_seed_10
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 11 -o mash_cos_sim_mat_k_11_seed_11
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 12 -o mash_cos_sim_mat_k_11_seed_12
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 13 -o mash_cos_sim_mat_k_11_seed_13
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 14 -o mash_cos_sim_mat_k_11_seed_14
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 15 -o mash_cos_sim_mat_k_11_seed_15
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 16 -o mash_cos_sim_mat_k_11_seed_16
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 17 -o mash_cos_sim_mat_k_11_seed_17
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 18 -o mash_cos_sim_mat_k_11_seed_18
python make_sketches.py -g ../ecoli_genomes/ -k 11 -s 19 -o mash_cos_sim_mat_k_11_seed_19
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 0 -o mash_cos_sim_mat_k_21_seed_0
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 1 -o mash_cos_sim_mat_k_21_seed_1
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 2 -o mash_cos_sim_mat_k_21_seed_2
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 3 -o mash_cos_sim_mat_k_21_seed_3
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 4 -o mash_cos_sim_mat_k_21_seed_4
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 5 -o mash_cos_sim_mat_k_21_seed_5
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 6 -o mash_cos_sim_mat_k_21_seed_6
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 7 -o mash_cos_sim_mat_k_21_seed_7
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 8 -o mash_cos_sim_mat_k_21_seed_8
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 9 -o mash_cos_sim_mat_k_21_seed_9
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 10 -o mash_cos_sim_mat_k_21_seed_10
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 11 -o mash_cos_sim_mat_k_21_seed_11
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 12 -o mash_cos_sim_mat_k_21_seed_12
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 13 -o mash_cos_sim_mat_k_21_seed_13
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 14 -o mash_cos_sim_mat_k_21_seed_14
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 15 -o mash_cos_sim_mat_k_21_seed_15
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 16 -o mash_cos_sim_mat_k_21_seed_16
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 17 -o mash_cos_sim_mat_k_21_seed_17
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 18 -o mash_cos_sim_mat_k_21_seed_18
python make_sketches.py -g ../ecoli_genomes/ -k 21 -s 19 -o mash_cos_sim_mat_k_21_seed_19
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 0 -o mash_cos_sim_mat_k_31_seed_0
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 1 -o mash_cos_sim_mat_k_31_seed_1
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 2 -o mash_cos_sim_mat_k_31_seed_2
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 3 -o mash_cos_sim_mat_k_31_seed_3
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 4 -o mash_cos_sim_mat_k_31_seed_4
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 5 -o mash_cos_sim_mat_k_31_seed_5
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 6 -o mash_cos_sim_mat_k_31_seed_6
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 7 -o mash_cos_sim_mat_k_31_seed_7
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 8 -o mash_cos_sim_mat_k_31_seed_8
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 9 -o mash_cos_sim_mat_k_31_seed_9
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 10 -o mash_cos_sim_mat_k_31_seed_10
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 11 -o mash_cos_sim_mat_k_31_seed_11
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 12 -o mash_cos_sim_mat_k_31_seed_12
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 13 -o mash_cos_sim_mat_k_31_seed_13
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 14 -o mash_cos_sim_mat_k_31_seed_14
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 15 -o mash_cos_sim_mat_k_31_seed_15
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 16 -o mash_cos_sim_mat_k_31_seed_16
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 17 -o mash_cos_sim_mat_k_31_seed_17
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 18 -o mash_cos_sim_mat_k_31_seed_18
python make_sketches.py -g ../ecoli_genomes/ -k 31 -s 19 -o mash_cos_sim_mat_k_31_seed_19
